services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: sentinel-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sentinel_db
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: postgres
    volumes:
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: sentinel-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: